### ISSUE TITLE
Getting This Error

### ISSUE THREAD

**Issue by Hamisoptimistic** [Gh0stExp10it/Flow.Launcher.Plugin.Ollama#13]
[Uploading 2024-08-17.txt…]()
Flow Launcher version: 1.18.0
OS Version: 22631.3737
IntPtr Length: 8
x64: True

Python Path: C:\Users\Hamim\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Users\Hamim\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 08/17/2024 15:05:19
Exception:
Ollama Exception: 
Websites: https://github.com/Gh0stExp10it/Flow.Launcher.Plugin.Ollama
Author: Gh0stExp10it
Version: 1.0.4
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: ERROR:query.Query:[WinError 10061] No connection could be made because the target machine actively refused it

 ---> System.IO.InvalidDataException: ERROR:query.Query:[WinError 10061] No connection could be made because the target machine actively refused it

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Gh0stExp10it** [comment]
The error states that no connection could be established, because the target machine refused it. What does the configuration of the plugin look like? Have changes been made to the default values [Default Settings](https://github.com/Gh0stExp10it/Flow.Launcher.Plugin.Ollama?tab=readme-ov-file#settings)?

What does the Ollama Servers states, when you call http://localhost:11434/ in your local browser? Ideally, a response “Ollama is running” should appear there.

**Comment by Gh0stExp10it** [comment]
Still an issue? For further analysis I need, as mentioned before, more information. If there is no response, I will close this issue.
